apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: sampleweb-demo
        image: demodevopsvibi.azurecr.io/sampleweb:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: sampleweb-service
spec:
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
